name: CI

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test verify.sh itself
        run: (cd example && ./test.sh | ../verify.sh -t verify-cli-bash)

      - name: failure returns non-zero exit code
        run: '! (./verify.sh -t failing-test -d echo <<< "input")'

